spring.application.name=E-Commerce_OMS

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_oms
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Mytoshika@123

#MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/ecommerce_oms_reviews

# Liquibase
spring.liquibase.change-log=classpath:/db/changelog/changelog.sql

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=mytaushikasecratekey@123987567123
jwt.expiration=600000

#Mail Sender
spring.mail.host = smtp.gmail.com
spring.mail.port = 587

spring.mail.username = mytoshikademo@gmail.com
spring.mail.password = hwifebzvzrabocod

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#Redis & Cache Configuration
spring.data.redis.host = localhost
spring.data.redis.port = 6379

spring.cache.type = redis
spring.cache.redis.time-to-live = 1800000


# Keycloak OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/ecommerce-oms

# Keycloak
keycloak.server-url=http://localhost:8180
keycloak.realm=ecommerce-oms

# AdminAPI
keycloak.username=admin
keycloak.password=Admin@123

# KeyCloak  Client
keycloak.client-id=ecommerce-oms-backend
keycloak.client-secret=98Mu7HnqxRt8TiKWmO1lgTyjYtl4V0TmSGQmnjAPYLeemdGclRLAKZ3kBrDdKxHT85XuCzjwLfoG8y0nO9ngZ0
